version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:

      MYSQL_USER: user123
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: db123
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "13000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://user123:password123@db:3306/db123
      DB_HOST: "db"
      DB_USER: "user123"
      DB_PASSWORD: "password123"
      DB_NAME: "db123"
      DB_PORT: "3306"

volumes:
  db_data:
